AllCops:
  Exclude:
    - spec/**/*
    - ognivo.gemspec

Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 90

Style/PerlBackrefs:
  Enabled: false

# lower to 15
Metrics/AbcSize:
  Max: 16
